on:
  push:
    tags: v*.*
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: âœ… Checkout repository
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: ğŸ§ª Run unit tests
        run: ./build.sh test
  create-github-release:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - name: âœ… Checkout repository
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: ğŸ› ï¸ Build release assets
        run: ./build.sh pack --configuration Release
      - name: ğŸš€ Create GitHub release and upload asset files
        run: ./build.sh create-github-release
        env:
          GITHUB_TOKEN: ${{ github.token }}
    permissions:
      contents: write
